Add test function to 20_vault/hook and better error output.
So a passphrase read attempt can be made without having to rebuild an
initramfs just to find out

20_vault/hook test zpoolName/datasetName

diff --git a/modules.d/20_vault/hook b/modules.d/20_vault/hook
--- a/modules.d/20_vault/hook
+++ b/modules.d/20_vault/hook
@@ -1,5 +1,46 @@
 #!/bin/bash
 
+function checkVaultTokenValid {
+    # Do a self-lookup API call before waiting any time
+  URL="https://${vaultHost}/v1/auth/token/lookup-self"
+  result=$(curl --fail -sq -H "X-Vault-Token: $vaultToken" -X GET "$URL")
+  curlReturnCode=$?
+  if [ "$result" == '{"errors":["permission denied"]}' ]
+  then
+    echo -e "\t\tPermission Denied from Vault trying to lookup own token. Token may be expired or invalid."
+  else
+    echo -e "\t\tAccessing vault [$vaultHost] successful, TOKEN IS VALID."
+  fi
+}
+
+function attemptVaultRead {
+    URL="https://${vaultHost}/v1/${vaultKvEngineName}/${vaultRootSearchPath}/${lockedDataset}"
+    result=$(curl --fail -sq -H "X-Vault-Token: $vaultToken" -X GET "$URL")
+    curlReturnCode=$?
+
+
+    if [ $curlReturnCode -eq 22 ]
+    then
+        # Try again to catch the error
+      responseCode=$(curl --fail -H "X-Vault-Token: $vaultToken" -X GET "$URL" 2>&1 | grep -oP '[0-9]{3}$')
+      if [ "$responseCode" -eq 403 ]
+      then
+        echo -e "\t\tVault returned a 403 for ${lockedDataset}. Token may not have access to the secret"
+      elif [ "$responseCode" -eq 404 ]
+      then
+        echo -e "\t\tVault returned a 404 for ${lockedDataset}. The secret may not exist?"
+      else
+      echo -e "\t\tVault returned an error trying to read your unlock passphrase. Does the kv secret exist?"
+      fi
+      return 1
+    elif [ "$result" == '{"errors":["permission denied"]}' ]
+    then
+      echo -e "\t\tPermission Denied trying to read vault secret for ${dataset} with URL: $URL"
+    else
+      vaultPassphraseResult="$(echo $result | jq '.data.data.passphrase')"
+    fi
+}
+
 function hook {
   if [ -f /etc/zfsUnlocker/zfsUnlocker.conf ]
   then
@@ -9,31 +50,53 @@ function hook {
     return 1
   fi
 
-    # Try unlocking root dataset first. Then try unlocking other datasets with an unavailable keystatus while we're at it.
+    checkVaultTokenValid|| exit 1
 
-  for lockedDataset in $dataset $(zfs get -H -o name,value keystatus | grep unavailable | grep -v '@' | cut -f1)
+    # Try unlocking all datasets with an 'unavailable' keystatus, but root first.
+
+  if [ -n "$testDataset" ]
+  then 
+    lockedDatasets="$testDataset"
+  else
+    lockedDatasets="$dataset $(zfs get -H -o name,value keystatus 2>/dev/null | grep unavailable | grep -v '@' | cut -f1)"
+  fi
+
+  for lockedDataset in $lockedDatasets
   do
-    if ! zfs get -H -o name,value keystatus ${lockedDataset} | grep unavailable >/dev/null 2>&1 ; then continue ; fi # If not still locked, skip
-    URL="https://${vaultHost}/v1/${vaultKvEngineName}/${vaultRootSearchPath}/${lockedDataset}"
+    if ! zfs get -H -o name,value keystatus ${lockedDataset} 2>/dev/null | grep unavailable >/dev/null 2>&1 && [ ! -n "$testDataset" ] ; then continue ; fi # If not still locked, skip
+    [ -n "$testDataset" ] && echo -e "\t\tAttempting unlock of: $lockedDataset"
 
-    result=$(curl -sq -H "X-Vault-Token: $vaultToken" -X GET "$URL")
+    attemptVaultRead || exit 1
 
-    if [ "$result" == '{"errors":["permission denied"]}' ]
+    if [ -n "$testDataset" ]
     then
-      echo -e "\t\tCouldn't find a Vault secret for ${dataset} with URL: $URL"
-    elif [ "$result" == '{"errors":[]}' ]
-    then
-      echo -e "\t\tVault permission error, is the token valid?"
+      echo -e "\t\t$(wc -m <<<"$vaultPassphraseResult") char length passphrase successfully found for $testDataset"
     else
-      vaultResult="$(echo $result | jq '.data.data.passphrase')"
-      echo -e "\t\tTrying to unlock $lockedDataset"
-      eval yes "$vaultResult" | zfs load-key -a # Try findings
+      eval yes "$vaultPassphraseResult" | zfs load-key -a # Try findings
     fi
   done
+}
+
+
+function test { # For someone to test the hook with before rebooting
+  echo "This is a test function to try reading a vault dataset secret before rebooting."
+
 }
 
 function cleanup {
  : 
 }
 
-$1
+if [ "$1" == 'test' ]
+then
+  echo "Entering test mode."
+
+  if [ "$2" ]
+  then
+    testDataset=$2 hook
+  else
+    echo "Please provide a dataset name as an argument."
+  fi
+else
+  $1
+fi
